# Generated by Django 2.2.14 on 2020-07-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200719_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='Yosua', max_length=20),
        ),
    ]
